name: build
on:
  push:
    branches-ignore:
      - '**pages**'
  pull_request:
    branches-ignore:
      - '**pages**'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [RelWithDebInfo]
        generator: [Ninja]
        include:
          - os: windows-2022
            build_type: RelWithDebInfo
            generator: "Visual Studio 17 2022"
            arch: amd64
            toolset: -T v143
          - os: windows-2019
            build_type: RelWithDebInfo
            generator: "Visual Studio 16 2019"
            arch: amd64_x86
            toolset: -T v141_xp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Initialise MSVC environment
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - uses: lukka/get-cmake@latest

      - name: Setup Macos dependencies
        if: ${{ runner.os == 'macOS' }}
        run: brew install sdl2 sdl2_ttf

      - name: Set up Linux dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install libsdl2-ttf-dev

      - run: mkdir ${{ env.CPM_SOURCE_CACHE }}

      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CPM_SOURCE_CACHE }}
            ${{ github.workspace }}/build/_deps
            ${{ github.workspace }}/build/**/cmake_pch.*
          key: ${{ matrix.os }}-${{ hashFiles('CMakeLists.txt','.github/workflows/build.yml') }}
          
      - name: Build
        run: |
          cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.toolset }}
          cmake --build build
          
      - name: Tar output on Unix systems
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd ${{ github.workspace }}/build
          tar cf haiyajan-menu.tar haiyajan-menu*

      - name: Get Short SHA
        id: vars
        run: echo "{sha_short}=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}${{ matrix.arch}}-${{ matrix.build_type }}-${{ steps.vars.outputs.sha_short }}
          path: |
            ${{ github.workspace }}/build/haiyajan-menu.tar
            ${{ github.workspace }}/build/**/haiyajan-menu.exe
            ${{ github.workspace }}/build/**/haiyajan-menu.pdb
