name: build
on: [push]

jobs:
  job:
    name: ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgPackages: 'sdl2 sdl2-ttf'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgPackages: 'sdl2 sdl2-ttf'
          - os: macos-latest
            triplet: x64-osx
            vcpkgPackages: 'sdl2 sdl2-ttf'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: 'master'
          path: '${{ runner.workspace }}/b/vcpkg'
          
      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          
      - name: Run CMake+Ninja with triplet (cmd)
        uses: lukka/run-cmake@main
        id: runcmake_cmd
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          vcpkgTriplet: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
