name: build
on: [push]

jobs:
  job:
    name: ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        include:
#          - os: windows-latest
#            triplet: x64-windows
#            vcpkgPackages: 'sdl2 sdl2-ttf'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgPackages: 'sdl2 sdl2-ttf'
#          - os: macos-latest
#            triplet: x64-osx
#            vcpkgPackages: 'sdl2 sdl2-ttf'

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Acquire vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
