name: Debug

on: [push]

jobs:
  build:
    name: Debug build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [debug]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkg-path: "$env:VCPKG_INSTALLATION_ROOT"
            platform_name: "-A x64"
          - os: windows-latest
            triplet: x86-windows
            vcpkg-path: "$env:VCPKG_INSTALLATION_ROOT"
            platform_name: "-A Win32"
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkg-path: "$VCPKG_INSTALLATION_ROOT"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install Dependencies
      run: vcpkg install --triplet=${{ matrix.triplet }} sdl2 sdl2-ttf
      
    - name: Configure Cmake
      run: cmake -B ${{ matrix.build_type }}-build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.platform_name }}
        
    - name: Build
      run: cmake --build ${{ matrix.build_type }}-build --config ${{ matrix.build_type }}
      
    - name: Pack output
      run: cpack --config ${{ matrix.build_type }}-build/CPackConfig.cmake -G ZIP
      
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: haiyajan-menu-${{ matrix.triplet }}-${{ github.run_number }}
        path: ${{ github.workspace }}/haiyajan-menu*.zip
        
