name: build
on: [push]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [RelWithDebInfo]
        generator: [Ninja]
        include:
          - os: windows-latest
            build_type: RelWithDebInfo
            generator: "Visual Studio 16 2019"
            arch: amd64
            toolset: -T v142
          - os: windows-latest
            build_type: RelWithDebInfo
            generator: "Visual Studio 16 2019"
            arch: amd64_x86
            toolset: -T v141_xp

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Initialise MSVC environment
        if: "contains(matrix.os, 'windows')"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - uses: lukka/get-cmake@v3.21.1
          
      - name: Build
        run: |
          cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.toolset }}
          cmake --build build
          
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}${{ matrix.arch}}-${{ matrix.build_type }}-#${{ github.run_number }}
          path: |
            ${{ github.workspace }}/build/haiyajan-menu
            ${{ github.workspace }}/build/haiyajan-menu.app
            ${{ github.workspace }}/build/**/haiyajan-menu.exe
            ${{ github.workspace }}/build/**/haiyajan-menu.pdb
