name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.build_type }} build for ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Debug, Release]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkg-path: "C:\\vcpkg"
            arch: amd64
            generator: "'NMake Makefiles'"
          - os: windows-latest
            triplet: x86-windows
            vcpkg-path: "C:\\vcpkg"
            arch: amd64_x86
            generator: "'NMake Makefiles'"
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkg-path: "$VCPKG_INSTALLATION_ROOT"
            generator: "'Unix Makefiles'"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Initialise MSVC environment
      if: contains(matrix.triplet, "windows")
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        
    - name: Install Dependencies
      run: vcpkg install --triplet=${{ matrix.triplet }} sdl2 sdl2-ttf
      
    - name: Configure Cmake
      run: cmake -S . -B build -G ${{ matrix.generator }} -DCMAKE_TOOLCHAIN_FILE=${{ matrix.vcpkg-path }}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
      
    - name: Pack
      run: cpack -G ZIP --config build/CPackConfig.cmake
      
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.triplet }}-${{ matrix.build_type }}-#${{ github.run_number }}
        path: ${{ github.workspace }}/haiyajan-menu*.zip
        
