name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\ext\MSVC\haiyajan-menu.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  COMPANY: Deltabeard
  DESCRIPTION: "Menu UI for Haiyajan"
  LICENSE: LGPL-3.0-or-later

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - name: Set Git Hash Environment Variable
      shell: bash
      run: |
        echo 'BUILD_ID<<EOF' >> $GITHUB_ENV
        git describe --tags --always --dirty="-dirty" --abbrev=10 >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo "$GITHUB_ENV" > BUILD_ID

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        nuget restore ${{env.SOLUTION_FILE_PATH}}
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /p:GIT_VER=${{env.BUILD_ID}} /p:COMPANY=${{env.COMPANY}} /p:DESCRIPTION="${{env.DESCRIPTION}}" /p:LICENSE=${{env.LICENSE}} ${{env.SOLUTION_FILE_PATH}}

    - name: Prepare additional files for artifact
      shell: bash
      run: |
        mv LICENSE README.md BUILD_ID ./ext/MSVC
    
    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: haiyajan-menu-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}
        path: |
          ext/MSVC/${{env.BUILD_CONFIGURATION}}/${{env.BUILD_PLATFORM}}/*.exe
          ext/MSVC/${{env.BUILD_CONFIGURATION}}/${{env.BUILD_PLATFORM}}/*.dll
          ext/MSVC/LICENSE
          ext/MSVC/README.md
          ext/MSVC/BUILD_ID
