name: Debug

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install Dependencies
      run: vcpkg install --triplet=x64-windows sdl2 sdl2-ttf
      
    - name: Configure Cmake
      run: cmake -B ${{github.workspace}}/${{env.BUILD_TYPE}}-build -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_TYPE}}-build --config ${{env.BUILD_TYPE}}
      
    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: haiyajan-menu-${{env.BUILD_PLATFORM}}-${{github.run_number}}
        path: |
          ${{github.workspace}}/README.md
          ${{github.workspace}}/LICENSE
          ${{github.workspace}}/${{env.BUILD_TYPE}}-build/*
        
