name: MSBuild

on: [push]

env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  COMPANY: Deltabeard
  DESCRIPTION: "Menu UI for Haiyajan"
  LICENSE: LGPL-3.0-or-later

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v7
      with:
        setupOnly: true
        
    - name: Install Dependencies
      shell: bash
      run: $VCPKG_ROOT/vcpkg install sdl2 sdl2-ttf
    
    - name: Configure and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        useVcpkgToolchainFile: true
        buildWithCMake: true
