# Compile builds for new release
name: release
on: 
  push:
    tags:
    - '*'

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch_label }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Release
            generator: Ninja
            arch_label: x86_64
            
          - os: macos-latest
            build_type: Release
            generator: Ninja
            arch_label: x86_64
            
          - os: windows-latest
            build_type: Release
            generator: "Visual Studio 16 2019"
            arch: amd64
            toolset: -T v142
            arch_label: x86_64
            
          - os: windows-latest
            build_type: Release
            generator: "Visual Studio 16 2019"
            arch: amd64_x86
            toolset: -T v141_xp
            os_label: Windows
            arch_label: x86_32

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Initialise MSVC environment
        if: "contains(matrix.os, 'windows')"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - uses: lukka/get-cmake@v3.21.1
          
      - name: Build
        run: |
          cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.toolset }}
          cmake --build build
          
      - name: Tar output on Unix systems
        if: "contains(matrix.os, 'windows') == false"
        working-directory: ${{ github.workspace }}/build
        run: tar cf haiyajan-menu-${{ env.GITHUB_REF }}.tar haiyajan-menu*
          
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.arch_label }}
          path: |
            ${{ github.workspace }}/build/haiyajan-menu-${{ env.GITHUB_REF }}.tar
            ${{ github.workspace }}/build/**/haiyajan-menu.exe
            ${{ github.workspace }}/build/**/haiyajan-menu.pdb

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/artifacts
      
      - name: Create release files
        working-directory: ${{ github.workspace }}/artifacts
        run: |
          find ./
          tar cJf Haiyajan-menu-${{ env.GITHUB_REF }}-Linux-x86_64.tar.xz Linux-x86_64/*
          tar cJf Haiyajan-menu-${{ env.GITHUB_REF }}-macOS-x86_64.tar.xz macOS-x86_64/*
          zip -Rj9 Haiyajan-menu-${{ env.GITHUB_REF }}-Windows-x86_64.zip Windows-x86_64/*.exe
          zip -Rj9 Haiyajan-menu-${{ env.GITHUB_REF }}-Windows-x86_32.zip Windows-x86_32/*.exe
        
      - uses: softprops/action-gh-release@v1
        with:
          files: |
           Haiyajan-menu-${{ env.GITHUB_REF }}-Linux-x86_64.tar.xz
           Haiyajan-menu-${{ env.GITHUB_REF }}-macOS-x86_64.tar.xz
           Haiyajan-menu-${{ env.GITHUB_REF }}-Windows-x86_64.zip
           Haiyajan-menu-${{ env.GITHUB_REF }}-Windows-x86_32.zip
